name: sweetpotatoes
favicon: null
layout_spectrum: 0.6549273345153779
typography_spectrum: 0.5074422697070986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.46981938858516514
  lightness: 0.1279066512361169
  saturation: 0.23254055925644934
  rhythmicContrast: 0.03235685219988227
purpose: []
